# Build customization
project_name: DeployEvents
archive:
  name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
  wrap_in_directory: true

builds:
  -
    binary: wait-deploy-client
    main: ./client/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    ldflags: -s -w -a -installsuffix cgo
  -
    binary: deploy-server
    main: ./server/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    ldflags: -s -w -a -installsuffix cgo

release:
  draft: false
  prerelease: false
  name_template: "{{.ProjectName}}-v{{.Version}}"
  disable: true